"""persist animation settings for resume

Revision ID: 007410dee79a
Revises: 707c556950eb
Create Date: 2026-08-24 21:40:18.214205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "007410dee79a"
down_revision: str | Sequence[str] | None = "707c556950eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generation_jobs",
        sa.Column("animate_scenes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("generation_jobs", sa.Column("video_provider", sa.String(), nullable=True))
    op.add_column("generation_jobs", sa.Column("animate_prompt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_jobs", "animate_prompt")
    op.drop_column("generation_jobs", "video_provider")
    op.drop_column("generation_jobs", "animate_scenes")
    # ### end Alembic commands ###
