"""remember the reviewers chosen accent and border

Revision ID: 0d2302d7007d
Revises: 94044cf93831
Create Date: 2026-09-02 11:10:31.557140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d2302d7007d"
down_revision: str | Sequence[str] | None = "94044cf93831"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("generation_jobs", sa.Column("decor_accent", sa.String(), nullable=True))
    op.add_column("generation_jobs", sa.Column("decor_border_width", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_jobs", "decor_border_width")
    op.drop_column("generation_jobs", "decor_accent")
    # ### end Alembic commands ###
