"""record generated-background settings on generation and scene jobs

Revision ID: 2f878966c440
Revises: 9c202e2d146f
Create Date: 2026-08-25 15:19:27.515795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f878966c440"
down_revision: str | Sequence[str] | None = "9c202e2d146f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generation_jobs",
        sa.Column("outpaint_scenes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("generation_jobs", sa.Column("image_provider", sa.String(), nullable=True))
    op.add_column("generation_jobs", sa.Column("outpaint_prompt", sa.String(), nullable=True))
    op.add_column("scene_jobs", sa.Column("image_provider", sa.String(), nullable=True))
    op.add_column("scene_jobs", sa.Column("outpaint_prompt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scene_jobs", "outpaint_prompt")
    op.drop_column("scene_jobs", "image_provider")
    op.drop_column("generation_jobs", "outpaint_prompt")
    op.drop_column("generation_jobs", "image_provider")
    op.drop_column("generation_jobs", "outpaint_scenes")
    # ### end Alembic commands ###
