"""record what a vision model saw in each generated shot

Revision ID: 5a3057c1499a
Revises: 45f1b54e4190
Create Date: 2026-08-31 16:31:08.527668

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a3057c1499a"
down_revision: str | Sequence[str] | None = "45f1b54e4190"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scene_jobs",
        sa.Column("identity_check", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scene_jobs", "identity_check")
    # ### end Alembic commands ###
