"""per-scene jobs and resume metadata

Revision ID: 707c556950eb
Revises: 03ed1158ea57
Create Date: 2026-08-24 21:34:19.461994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "707c556950eb"
down_revision: str | Sequence[str] | None = "03ed1158ea57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("visual_source", sa.String(), nullable=True),
        sa.Column("video_provider", sa.String(), nullable=True),
        sa.Column("animate_prompt", sa.String(), nullable=True),
        sa.Column("clip_path", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "scene_id", name="uq_scene_jobs_job_scene"),
    )
    op.create_index(op.f("ix_scene_jobs_job_id"), "scene_jobs", ["job_id"], unique=False)
    op.add_column("generation_jobs", sa.Column("work_dir", sa.String(), nullable=True))
    op.add_column("generation_jobs", sa.Column("voice_sample", sa.String(), nullable=True))
    op.add_column("generation_jobs", sa.Column("music_track", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_jobs", "music_track")
    op.drop_column("generation_jobs", "voice_sample")
    op.drop_column("generation_jobs", "work_dir")
    op.drop_index(op.f("ix_scene_jobs_job_id"), table_name="scene_jobs")
    op.drop_table("scene_jobs")
    # ### end Alembic commands ###
