"""record whether a person approved a version

Review state is its own column rather than another JobStatus value: status
says whether the run finished, and a finished run stays unreviewed until a
person looks at it.


Revision ID: 94044cf93831
Revises: 5a3057c1499a
Create Date: 2026-09-01 11:03:44.101710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94044cf93831"
down_revision: str | Sequence[str] | None = "5a3057c1499a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, not just the model-side default: every job that already
    # exists needs a value the moment the column appears, and "pending" is
    # exactly right for them — nobody has reviewed any of them.
    op.add_column(
        "generation_jobs",
        sa.Column("review_state", sa.String(), nullable=False, server_default="pending"),
    )
    op.add_column("generation_jobs", sa.Column("review_note", sa.String(), nullable=True))
    op.add_column(
        "generation_jobs", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_jobs", "reviewed_at")
    op.drop_column("generation_jobs", "review_note")
    op.drop_column("generation_jobs", "review_state")
    # ### end Alembic commands ###
