"""record when a job's rendered files were cleaned up

Revision ID: 9c202e2d146f
Revises: 007410dee79a
Create Date: 2026-08-25 14:10:41.939185

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c202e2d146f"
down_revision: str | Sequence[str] | None = "007410dee79a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generation_jobs", sa.Column("cleaned_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_jobs", "cleaned_at")
    # ### end Alembic commands ###
