"""scene props and per-scene prop specs

Revision ID: aca0dd58a857
Revises: 0d2302d7007d
Create Date: 2026-09-03 16:06:00.175577

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aca0dd58a857"
down_revision: str | Sequence[str] | None = "0d2302d7007d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generation_jobs",
        sa.Column("prop_specs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "scene_jobs", sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scene_jobs", "props")
    op.drop_column("generation_jobs", "prop_specs")
    # ### end Alembic commands ###
